# /.github/workflows/deploy.yml
# Purpose: Deploys the latest published release to production. Only runs on release events for full traceability.
name: 🚀 Enterprise Release Deployment

on:
  release:
    types: [published]

jobs:
  deploy-production:
    name: 🚀 Deploy to Production (Release Only)
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      deployment_target: 'Hostinger (Production)'
    secrets:
      HOSTINGER_FTP_USERNAME: ${{ secrets.HOSTINGER_FTP_USERNAME }}
      HOSTINGER_FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }} 