# /.github/workflows/deploy-on-push.yml
# Purpose: Deploys the latest code to production on every push to main for continuous delivery.
name: 🚀 Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      deployment_target: 'Hostinger (Production)'
    secrets:
      HOSTINGER_FTP_USERNAME: ${{ secrets.HOSTINGER_FTP_USERNAME }}
      HOSTINGER_FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }} 